version: '3.7'

services:

  server:
    container_name: pagarme
    build:
      target: builder
      context: .
    ports:
      - "8080:8080"
    depends_on:
        - postgres
    env_file:
      - .env
    network_mode: host
    entrypoint: ["/go/bin/server"]

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payme
    ports:
      - 5432:5432
    volumes:
      - ./docs/sql/schema_db.sql:/docker-entrypoint-initdb.d/init.sql